name:                my-project
version:             0.1.0.0
github:              "iu-haskell-fall-2018/my-project"
license:             BSD3
author:              "Nickolay Kudasov"
maintainer:          "n.kudasov@innopolis.ru"
copyright:           "2018 Innopolis University"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iu-haskell-fall-2018/my-project#readme>

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  my-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-project

tests:
  my-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-project
